name: MobSF

on:
  push:
    branches: [ "master", "developer" ]
  pull_request:
    branches: [ "master", "developer" ]
  schedule:
    - cron: '30 9 * * 2'

# Define permissões no nível do workflow
permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  mobile-security:
    # Importante: não sobrescreva as permissões aqui
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: . --sarif --output results.sarif || true

      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Comment on PR if issues found
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🔒 MobSF encontrou problemas de segurança \n\n Verifique a aba Security > Code scanning alerts para mais detalhes. \n\n Os problemas encontrados devem ser corrigidos antes do merge.`
            });